version: "3"

services:
  react:
    build: react-app
    ports:
      # container port
      - "3000:3000"
  express:
    build: node-app
    ports:
      # container port
      - "5000:5000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
